openapi: 3.0.1
info:
  title: JWT Security API
  description: POC for JWT Authentication and Authorization..!!
  version: "2.0"
servers:
- url: http://localhost:9090
  description: Generated server url
paths:
  /authenticate:
    post:
      tags:
      - welcome-controller
      operationId: generateToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /:
    get:
      tags:
      - welcome-controller
      operationId: welcome
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    AuthRequest:
      type: object
      properties:
        userName:
          type: string
        password:
          type: string
